custom:
  thread-pool:
    core-pool-size: 8 # 线程池长期维持的线程数 默认 8
    maximum-pool-size: 10 # 线程数的上限 默认 10
    capacity: 512 # 任务的排队队列 默认 512

trade:
  thread:
    msg:
      num: 8
agent:
  cache:
    path: D:\work\2_workspace\my-project\platform-aix-framework\cache
    clean: 0 0 16 ? * MON-FRI


#配置文件加密解密
jasypt:
  encryptor:
    bean: stringEncryptor

application:
  cache:
    file: classpath:aix-ehcache.xml
  runOptimize: N #Y表示业务代码做过启动优化，N表示业务代码没有做过启动优化