
logging:
  file: logs/platform-aix-framework.log
  level:
    root: INFO
    com:
      platform: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core: WARN
        jdbc:
          datasource: INFO
      # 获取到请求参数
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

spring:
  main:
    allow-bean-definition-overriding: true # 存在repo相同的情况 原phis的存储过程与aigw重名
  # 禁用 es 模块，需要启用es模块 注释此配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration

  profiles:
    include:
      - test
      - dataload  # dataload
      - redis     # redis
      - aix       # aix主工程
      - rmdb      # 关系型数据库
      - ignite    # ignite
      - es        # elasticsearch
      - rabbitmq  # rabbitmq
      - kafka     # kafka
