#==========关系型数据库配置===============#
spring:
  jpa:
    show-sql: true
    # 格式化输出sql
    #    properties:
    #      hibernate:
    #        format_sql: true
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          # 云服务器
#          url: jdbc:postgresql://pikai.cloud:5432/aixdb?stringtype=unspecified&currentSchema=aix
#          username: aix
#          password: ENC(SP+s1qUegeto17wVT0zDMH8K2bL2N4eM)
#          driver-class-name: org.postgresql.Driver # 3.2.0开始支持SPI可省略此配置
          # 本地
          url: jdbc:postgresql://localhost:5432/aixdb?stringtype=unspecified&currentSchema=aix
          username: postgres
          password: ENC(pISTbvTH8w1pnujfBd6Z5ORvhL1nIU8i)
          driver-class-name: org.postgresql.Driver # 3.2.0开始支持SPI可省略此配置
#          url: jdbc:oracle:thin:@//192.168.101.95:1521/orcl
#          username: BS306_DEV_20220707
#          password: BS306_DEV_20220707
#          driver-class-name: oracle.jdbc.driver.OracleDriver # 3.2.0开始支持SPI可省略此配置
#        slave_1:
#          url: jdbc:mysql://localhost:3306/dynamic?useSSL=false
#          username: root
#          password: root123
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        slave_2:
#          url: jdbc:oracle:thin:@//localhost:1521/orcl
#          username: AIX
#          password: AIX
#          driver-class-name: oracle.jdbc.driver.OracleDriver
        #        slave_2:
        #          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
        #          username: ENC(xxxxx)
        #          password: ENC(xxxxx)
        #          driver-class-name: com.mysql.cj.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2