# tomcat 访问端口
server:
  port: 8071
# mapper.xml文件位置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  boot:
    admin:
      client:
        url: http://localhost:9001
  application:
    name: aix-framework
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  #  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: google-client-id
#            client-secret: google-client-secret

# aix平台配置选项 框架访问端口
platform:
  aix:
    server:
      port: 16090
      thread-count: 8
      jetty:
        max-http-post-size: 81920
        max-http-header-size: 81920
    app-request-url: https://192.168.9.201/
    app-regist-file-folder: D:\upload  #D:\upload  # 201 APP注册文件存放目录 /var/www/html
    jwtconfig:
      access-token-expire: 10000
      refresh-token-expire: 10000
      access-token-secret: itsss
      refresh-token-secret: itsss
    redis:
      usecluster: false
      clusters: 101.35.80.154:7001,101.35.80.154:7002,101.35.80.154:7003,101.35.80.154:7004,101.35.80.154:7005,101.35.80.154:7006
    door:
      enable: true
      userStr: 10010,小周周
    # 跨域请求，设置* 默认允许所有的请求 http://localhost:7001
    crosurl: '*'
    ## openoffice 安装路径
    openofficeinstallationpath: C:\Program Files (x86)\OpenOffice 4\
    # mailtrap 邮箱配置：https://mailtrap.io/inboxes/3631079/messages
    mail:
      host: sandbox.smtp.mailtrap.io
      port: 2525
      userName: b8439d49070036
      passWord: 31a8feb02e4800
      # template 方式调用 mailtrap 发送验证邮件
      templateHost: send.api.mailtrap.io
      templateToken: 3a49845f4d61f5cbf4ffe7f358195ef7
      templateUUID: 96829dfe-5014-4687-af73-90d4794c34f6


middle:   # middle server 专项配置参数
  server:
    websocket:
      endpoint: /demo-zx-websocket-midserver  # Websocket通道地址
      test-topic-scheduled-fixed-delay: 1000  # 测试专用，定时广播topic的时间间隔，单位：毫秒
      websocket-message-broker-stats-period: 600  # 定时打印SpringBoot Websocket Session统计数值，时间间隔，单位：秒

# 开启监控所有项 sba配置选项
management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8080
spring:
  profiles: producer

---
server:
  port: 8081
spring:
  profiles: consumer1

---
server:
  port: 8082
spring:
  profiles: consumer2