server:
  port: 8069
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
  jpa:
    show-sql: true
    # 格式化输出sql
  #    properties:
  #      hibernate:
  #        format_sql: true
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:postgresql://101.35.80.154:5432/aix_db?stringtype=unspecified&currentSchema=aix
          username: postgres
          password: postgres
          driver-class-name: org.postgresql.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://101.35.80.154:3306/dynamic?useSSL=false
          username: root
          password: 1234
          driver-class-name: com.mysql.cj.jdbc.Driver
#        slave_2:
#          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
#          username: ENC(xxxxx)
#          password: ENC(xxxxx)
#          driver-class-name: com.mysql.cj.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
  redis:
    database: 0
    host: 101.35.80.154
    #    host: 114.55.11.51
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 20000


platform:
  aix:
    server:
      port: 16087
      thread-count: 8
      jetty:
        max-http-post-size: 81920
        max-http-header-size: 81920
    app-request-url: https://192.168.9.201/
    app-regist-file-folder: D:\upload  #D:\upload  # 201 APP注册文件存放目录 /var/www/html
    jwtconfig:
      access-token-expire: 10000
      refresh-token-expire: 10000
      access-token-secret: itsss
      refresh-token-secret: itsss

middle:   # middle server 专项配置参数
  server:
    websocket:
      endpoint: /demo-zx-websocket-midserver  # Websocket通道地址
      test-topic-scheduled-fixed-delay: 1000  # 测试专用，定时广播topic的时间间隔，单位：毫秒
      websocket-message-broker-stats-period: 10  # 定时打印SpringBoot Websocket Session统计数值，时间间隔，单位：秒

## dataloader配置
dataloader:
  main:
    runscript: false #是否一启动直接执行sql脚本
    url: jdbc:oracle:thin:@//192.168.90.230:1521/orcl
    drive: oracle.jdbc.driver.OracleDriver
    username: FAMS_FYL
    password: FAMS_FYL
    #filepath: D:\日常工作\fudian\06_脚本文件\处理脚本\升级脚本 # 脚本本地路径
    filepath: D:\\
    #filepath: D:\日常工作\fudian\06_脚本文件\测试 # 脚本本地路径
    # 以下配置是生成数据库表结构清单使用  默认只需要生成一次就好
    generate:
      imgentabledoc: false #是否一启动就生成数据库表结构
      fileoutputdir: E:\\
      enginefiletype: HTML  # value: HTML MD WORD
      filename: XX系统表结构