drop table if exists t_puzzle_history_list;
create table t_puzzle_history_list(
id int4  GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
thumbnail text,
complete_time  timestamp,
success boolean,
create_time timestamp not null
);
-- 为表添加注释
COMMENT ON TABLE t_puzzle_history_list IS '拼图历史记录表';

-- 为列添加注释
COMMENT ON COLUMN t_puzzle_history_list.id IS '主键';
COMMENT ON COLUMN t_puzzle_history_list.thumbnail IS '图片';
COMMENT ON COLUMN t_puzzle_history_list.complete_time IS '完成时间';
COMMENT ON COLUMN t_puzzle_history_list.success IS '是否成功';
COMMENT ON COLUMN t_puzzle_history_list.create_time IS '创建时间';


CREATE SEQUENCE
sqe_puzzle_history_list
INCREMENT 1        -- 步长
MINVALUE 1        -- 最小值
MAXVALUE 999999999    --最大值
START WITH 1    --起始值
CACHE 1;

-- 查询序列
select * from information_schema.sequences where sequence_schema = 'aix';